variables:
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/.cache/Cypress
  CLICOLOR: '1' # Make sure everything is colorful
  DOCKER_IMAGE: node:lts-alpine

image: $DOCKER_IMAGE

stages:
  - dependencies
  - test
  - deploy
  - verify

default:
  interruptible: true

cache: &global_cache
  key:
    files:
      - yarn.lock
    prefix: $CI_PROJECT_PATH_SLUG
  paths:
    - .cache
    - node_modules
    - packages/*/node_modules
  policy: pull

# =============== Dependencies
dependencies:
  stage: dependencies
  script:
    - yarn install --frozen-lockfile
  cache:
    <<: *global_cache
    policy: pull-push

# =============== Test
lint:
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn lint

typescript:
  stage: test
  script:
    - yarn workspace cypress tsc
    - yarn workspace example-app tsc

# =============== Verify
cypress:
  stage: verify
  image: cypress/browsers:node12.18.0-chrome83-ff77
  script:
    - yarn --frozen-lockfile
    # normally, we would test a staging app deployed in "deploy" stage
    - export CYPRESS_BASE_URL="https://kiwi.com"
    - yarn workspace cypress cypress run -b chrome --headless
  artifacts:
    when: on_failure
    expire_in: 3 days
    paths:
      - packages/cypress/assets
